package com.samsolutions.logistics.mainlogistics.repositories;

import com.samsolutions.logistics.mainlogistics.entities.Carriers;
import com.samsolutions.logistics.mainlogistics.entities.RoutesOnCarriers;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

@Repository
public interface RoutesOnCarriersRepository extends JpaRepository<RoutesOnCarriers,Long> {
    @Query(value = "SELECT PF.COUNTRY COUNTRY_FROM,PF.REGION REGION_FROM,PF.CITY CITY_FROM," +
            "PT.COUNTRY COUNTRY_TO,PT.REGION REGION_TO,PT.CITY CITY_TO, CA.CARRIER_NAME,CA.CAR_NAME,CA.VOLUME,CA.CAPACITY,CA.COST,RI.DATE_START,RI.DATE_FINISH,RI.LENGTH,RI.DURATION FROM ROUTES_ON_CARRIERS ROC" +
            " INNER JOIN ROUTES R INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
            " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
            " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
            " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID ORDER BY PF.CITY",
            countQuery = "SELECT count(*) FROM ROUTES_ON_CARRIERS ROC" +
                    " INNER JOIN ROUTES R INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
                    " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
                    " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
                    " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID",
            nativeQuery = true)
    Page<Object> findAllRoutesOrderByCityFrom(Pageable pageable);
    @Query(value = "SELECT PF.COUNTRY COUNTRY_FROM,PF.REGION REGION_FROM,PF.CITY CITY_FROM," +
            "PT.COUNTRY COUNTRY_TO,PT.REGION REGION_TO,PT.CITY CITY_TO, CA.CARRIER_NAME,CA.CAR_NAME,CA.VOLUME,CA.CAPACITY,CA.COST,RI.DATE_START,RI.DATE_FINISH,RI.LENGTH,RI.DURATION FROM ROUTES_ON_CARRIERS ROC" +
            " INNER JOIN ROUTES R INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
            " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
            " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
            " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID ORDER BY PF.COUNTRY",
            countQuery = "SELECT count(*) FROM ROUTES_ON_CARRIERS ROC" +
                    " INNER JOIN ROUTES R INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
                    " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
                    " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
                    " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID",
            nativeQuery = true)
    Page<Object> findAllRoutesOrderByCountryFrom(Pageable pageable);
    @Query(value = "SELECT PF.COUNTRY COUNTRY_FROM,PF.REGION REGION_FROM,PF.CITY CITY_FROM," +
            "PT.COUNTRY COUNTRY_TO,PT.REGION REGION_TO,PT.CITY CITY_TO, CA.CARRIER_NAME,CA.CAR_NAME,CA.VOLUME,CA.CAPACITY,CA.COST,RI.DATE_START,RI.DATE_FINISH,RI.LENGTH,RI.DURATION FROM ROUTES_ON_CARRIERS ROC" +
            " INNER JOIN ROUTES R INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
            " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
            " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
            " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID ORDER BY PF.CITY DESC",
            countQuery = "SELECT count(*) FROM ROUTES_ON_CARRIERS ROC" +
                    " INNER JOIN ROUTES R INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
                    " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
                    " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
                    " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID",
            nativeQuery = true)
    Page<Object> findAllRoutesOrderByCityFromDesc(Pageable pageable);
    @Query(value = "SELECT PF.COUNTRY COUNTRY_FROM,PF.REGION REGION_FROM,PF.CITY CITY_FROM," +
            "PT.COUNTRY COUNTRY_TO,PT.REGION REGION_TO,PT.CITY CITY_TO, CA.CARRIER_NAME,CA.CAR_NAME,CA.VOLUME,CA.CAPACITY,CA.COST,RI.DATE_START,RI.DATE_FINISH,RI.LENGTH,RI.DURATION FROM ROUTES_ON_CARRIERS ROC" +
            " INNER JOIN ROUTES R INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
            " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
            " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
            " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID ORDER BY PF.COUNTRY DESC",
            countQuery = "SELECT count(*) FROM ROUTES_ON_CARRIERS ROC" +
                    " INNER JOIN ROUTES R INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
                    " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
                    " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
                    " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID",
            nativeQuery = true)
    Page<Object> findAllRoutesOrderByCountryFromDesc(Pageable pageable);

    @Query(value = "SELECT PF.COUNTRY COUNTRY_FROM,PF.REGION REGION_FROM,PF.CITY CITY_FROM," +
            "PT.COUNTRY COUNTRY_TO,PT.REGION REGION_TO,PT.CITY CITY_TO, CA.CARRIER_NAME,CA.CAR_NAME,CA.VOLUME,CA.CAPACITY,CA.COST,RI.DATE_START,RI.DATE_FINISH,RI.LENGTH,RI.DURATION FROM ROUTES_ON_CARRIERS ROC" +
            " INNER JOIN ROUTES R INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
            " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
            " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
            " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID ORDER BY RI.DATE_START",
            countQuery = "SELECT count(*) FROM ROUTES_ON_CARRIERS ROC" +
                    " INNER JOIN ROUTES R INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
                    " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
                    " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
                    " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID",
            nativeQuery = true)
    Page<Object> findAllRoutesOrderByDateStart(Pageable pageable);
    @Query(value = "SELECT PF.COUNTRY COUNTRY_FROM,PF.REGION REGION_FROM,PF.CITY CITY_FROM," +
            "PT.COUNTRY COUNTRY_TO,PT.REGION REGION_TO,PT.CITY CITY_TO, CA.CARRIER_NAME,CA.CAR_NAME,CA.VOLUME,CA.CAPACITY,CA.COST,RI.DATE_START,RI.DATE_FINISH,RI.LENGTH,RI.DURATION FROM ROUTES_ON_CARRIERS ROC" +
            " INNER JOIN ROUTES R INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
            " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
            " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
            " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID ORDER BY RI.DATE_START DESC",
            countQuery = "SELECT count(*) FROM ROUTES_ON_CARRIERS ROC" +
                    " INNER JOIN ROUTES R INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
                    " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
                    " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
                    " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID",
            nativeQuery = true)
    Page<Object> findAllRoutesOrderByDateStartDesc(Pageable pageable);



    @Query(value = "SELECT PF.COUNTRY COUNTRY_FROM,PF.REGION REGION_FROM,PF.CITY CITY_FROM," +
            "PT.COUNTRY COUNTRY_TO,PT.REGION REGION_TO,PT.CITY CITY_TO, CA.CARRIER_NAME,CA.CAR_NAME,CA.VOLUME,CA.CAPACITY,CA.COST,RI.DATE_START,RI.DATE_FINISH,RI.LENGTH,RI.DURATION FROM ROUTES_ON_CARRIERS ROC" +
            " INNER JOIN ROUTES R INNER JOIN CONTACTS CON ON R.CONTACTS_ID=CON.ID INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
            " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
            " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
            " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID WHERE CON.EMAIL=?1 ORDER BY PF.CITY",
            countQuery = "SELECT count(*) FROM ROUTES_ON_CARRIERS ROC" +
                    " INNER JOIN ROUTES R INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
                    " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
                    " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
                    " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID",
            nativeQuery = true)
    Page<Object> findAllRoutesByEmailCreatorOrderByCityFrom(String  email,Pageable pageable);
    @Query(value = "SELECT PF.COUNTRY COUNTRY_FROM,PF.REGION REGION_FROM,PF.CITY CITY_FROM," +
            "PT.COUNTRY COUNTRY_TO,PT.REGION REGION_TO,PT.CITY CITY_TO, CA.CARRIER_NAME,CA.CAR_NAME,CA.VOLUME,CA.CAPACITY,CA.COST,RI.DATE_START,RI.DATE_FINISH,RI.LENGTH,RI.DURATION FROM ROUTES_ON_CARRIERS ROC" +
            " INNER JOIN ROUTES R INNER JOIN CONTACTS CON ON R.CONTACTS_ID=CON.ID INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
            " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
            " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
            " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID WHERE CON.EMAIL=?1 ORDER BY PF.COUNTRY",
            countQuery = "SELECT count(*) FROM ROUTES_ON_CARRIERS ROC" +
                    " INNER JOIN ROUTES R INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
                    " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
                    " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
                    " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID",
            nativeQuery = true)
    Page<Object> findAllRoutesByEmailCreatorOrderByCountryFrom(String  email,Pageable pageable);
    @Query(value = "SELECT PF.COUNTRY COUNTRY_FROM,PF.REGION REGION_FROM,PF.CITY CITY_FROM," +
            "PT.COUNTRY COUNTRY_TO,PT.REGION REGION_TO,PT.CITY CITY_TO, CA.CARRIER_NAME,CA.CAR_NAME,CA.VOLUME,CA.CAPACITY,CA.COST,RI.DATE_START,RI.DATE_FINISH,RI.LENGTH,RI.DURATION FROM ROUTES_ON_CARRIERS ROC" +
            " INNER JOIN ROUTES R INNER JOIN CONTACTS CON ON R.CONTACTS_ID=CON.ID INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
            " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
            " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
            " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID WHERE CON.EMAIL=?1 ORDER BY PF.CITY DESC",
            countQuery = "SELECT count(*) FROM ROUTES_ON_CARRIERS ROC" +
                    " INNER JOIN ROUTES R INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
                    " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
                    " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
                    " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID",
            nativeQuery = true)
    Page<Object> findAllRoutesByEmailCreatorOrderByCityFromDesc(String  email,Pageable pageable);
    @Query(value = "SELECT PF.COUNTRY COUNTRY_FROM,PF.REGION REGION_FROM,PF.CITY CITY_FROM," +
            "PT.COUNTRY COUNTRY_TO,PT.REGION REGION_TO,PT.CITY CITY_TO, CA.CARRIER_NAME,CA.CAR_NAME,CA.VOLUME,CA.CAPACITY,CA.COST,RI.DATE_START,RI.DATE_FINISH,RI.LENGTH,RI.DURATION FROM ROUTES_ON_CARRIERS ROC" +
            " INNER JOIN ROUTES R INNER JOIN CONTACTS CON ON R.CONTACTS_ID=CON.ID INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
            " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
            " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
            " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID WHERE CON.EMAIL=?1 ORDER BY PF.COUNTRY DESC",
            countQuery = "SELECT count(*) FROM ROUTES_ON_CARRIERS ROC" +
                    " INNER JOIN ROUTES R INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
                    " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
                    " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
                    " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID",
            nativeQuery = true)
    Page<Object> findAllRoutesByEmailCreatorOrderByCountryFromDesc(String  email,Pageable pageable);

    @Query(value = "SELECT PF.COUNTRY COUNTRY_FROM,PF.REGION REGION_FROM,PF.CITY CITY_FROM," +
            "PT.COUNTRY COUNTRY_TO,PT.REGION REGION_TO,PT.CITY CITY_TO, CA.CARRIER_NAME,CA.CAR_NAME,CA.VOLUME,CA.CAPACITY,CA.COST,RI.DATE_START,RI.DATE_FINISH,RI.LENGTH,RI.DURATION FROM ROUTES_ON_CARRIERS ROC" +
            " INNER JOIN ROUTES R INNER JOIN CONTACTS CON ON R.CONTACTS_ID=CON.ID INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
            " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
            " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
            " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID WHERE CON.EMAIL=?1 ORDER BY RI.DATE_START",
            countQuery = "SELECT count(*) FROM ROUTES_ON_CARRIERS ROC" +
                    " INNER JOIN ROUTES R INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
                    " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
                    " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
                    " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID",
            nativeQuery = true)
    Page<Object> findAllRoutesByEmailCreatorOrderByDateStart(String  email,Pageable pageable);
    @Query(value = "SELECT PF.COUNTRY COUNTRY_FROM,PF.REGION REGION_FROM,PF.CITY CITY_FROM," +
            "PT.COUNTRY COUNTRY_TO,PT.REGION REGION_TO,PT.CITY CITY_TO, CA.CARRIER_NAME,CA.CAR_NAME,CA.VOLUME,CA.CAPACITY,CA.COST,RI.DATE_START,RI.DATE_FINISH,RI.LENGTH,RI.DURATION FROM ROUTES_ON_CARRIERS ROC" +
            " INNER JOIN ROUTES R INNER JOIN CONTACTS CON ON R.CONTACTS_ID=CON.ID INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
            " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
            " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
            " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID WHERE CON.EMAIL=?1 ORDER BY RI.DATE_START DESC",
            countQuery = "SELECT count(*) FROM ROUTES_ON_CARRIERS ROC" +
                    " INNER JOIN ROUTES R INNER JOIN POINTS PF ON R.POINT_FROM_ID=PF.ID" +
                    " INNER JOIN POINTS PT ON R.POINT_TO_ID=PT.ID" +
                    " INNER JOIN ROUTES_INFO RI ON R.ID=RI.ROUTE_ID  ON ROC.ROUTES_ID=R.ID" +
                    " INNER JOIN CARRIERS CA ON ROC.CARRIERS_ID=CA.ID",
            nativeQuery = true)
    Page<Object> findAllRoutesByEmailCreatorOrderByDateStartDesc(String  email,Pageable pageable);
}
